"""
Alert evaluation engine testing active device metrics against rules, suppressing maintenance alarms,
and correlating alerts into actionable Incident tickets.
"""

from typing import List, Dict, Any, Optional
from datetime import datetime, timezone, timedelta
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, and_
from sqlalchemy.orm import selectinload
from backend.app.alerts.models import AlertRule, Alert, AlertSuppression, AlertSeverity, AlertStatus
from backend.app.devices.models import Device
from backend.app.incidents.models import Incident, IncidentSeverity, IncidentPriority, IncidentStatus
from backend.app.websocket_manager import ws_manager


class AlertRulesEngine:
    @staticmethod
    async def evaluate_device_metrics(db: AsyncSession, device: Device, metrics: Dict[str, Any]):
        """Evaluate real-time telemetry metrics against active alert rules."""
        # 1. Check if device is in active maintenance suppression window
        now = datetime.now(timezone.utc)
        supp_res = await db.execute(
            select(AlertSuppression).where(
                AlertSuppression.device_id == device.id,
                AlertSuppression.is_active == True,
                AlertSuppression.starts_at <= now,
                AlertSuppression.ends_at >= now,
            )
        )
        if supp_res.scalar_one_or_none():
            return  # Suppressed during maintenance

        # 2. Fetch active rules
        rules_res = await db.execute(select(AlertRule).where(AlertRule.is_enabled == True))
        rules = rules_res.scalars().all()

        for rule in rules:
            val = metrics.get(rule.metric_name)
            if val is None:
                continue

            # Evaluate condition
            triggered = False
            if rule.condition_op == "gt" and val > rule.threshold_value:
                triggered = True
            elif rule.condition_op == "lt" and val < rule.threshold_value:
                triggered = True
            elif rule.condition_op == "eq" and val == rule.threshold_value:
                triggered = True
            elif rule.condition_op == "ne" and val != rule.threshold_value:
                triggered = True

            if triggered:
                # Check for existing active alert for same rule & device
                existing_res = await db.execute(
                    select(Alert).where(
                        Alert.rule_id == rule.id,
                        Alert.device_id == device.id,
                        Alert.status == AlertStatus.ACTIVE,
                    )
                )
                existing = existing_res.scalar_one_or_none()
                if not existing:
                    # Create new alert
                    msg = f"{rule.name}: {rule.metric_name} is {val} (threshold {rule.threshold_value}) on {device.hostname}"
                    alert = Alert(
                        rule_id=rule.id,
                        device_id=device.id,
                        message=msg,
                        metric_name=rule.metric_name,
                        metric_value=float(val),
                        severity=rule.severity,
                        status=AlertStatus.ACTIVE,
                    )
                    db.add(alert)
                    await db.flush()

                    # Broadcast alert over WebSocket
                    await ws_manager.broadcast_alert({
                        "id": alert.id,
                        "device_id": device.id,
                        "hostname": device.hostname,
                        "message": msg,
                        "severity": rule.severity.value,
                        "triggered_at": datetime.now(timezone.utc).isoformat(),
                    })

                    # Auto-create incident if rule configured
                    if rule.auto_create_incident:
                        inc = Incident(
                            title=f"Automated Alarm: {msg}",
                            description=f"Auto-generated by Alert Rule #{rule.id} on device {device.hostname}",
                            severity=IncidentSeverity.HIGH if rule.severity == AlertSeverity.CRITICAL else IncidentSeverity.MEDIUM,
                            priority=IncidentPriority.P2,
                            status=IncidentStatus.OPEN,
                            affected_device_id=device.id,
                            related_alert_ids=[alert.id],
                        )
                        db.add(inc)

        await db.commit()
